# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd404cfc8f23d754aeb053b08431867b239f3e995347af3a808fa91bc26b78d8dd8e8050e5be5fbeaf0089cee87d066b2a98b99d5cbac96eb1fc0ece35530175

test:
  secret_key_base: cb2bab6b45bde36ffc1a65d988cb0fb304dd64443d9a79ab935a414e397577812dd14ba0cf9b1de98715b10c65e07dd98be04f7a3c50474ea66ccf58379464b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
